### PR TITLE
Handle exception that happen at data layer and logic

### LINKED ISSUE #90: refactor exceptions
clear out all the mess with exceptions

currently, the data layer doesn't throw necessary exceptions

the use case, in most cases, shouldn't throw a use case

there are some exceptions that are very specific to the data layer, like:
```
class WritingToCsvFileFaliureException(): Excetion(message)
class ReadingFromCsvFileFaliureException(): Excetion(message)
class PushingDataToMongoServerFaliureException(): Excetion(message)
class FetchingDataFromMongoServerFailureException(): Excetion(message)
```

these exceptions should not leave the data layer, so they should be mapped inside the repos to more general exceptions like:
```
open class StoringDataFaliureException(message: String): Excetion(message)  // this exception live in the logic layer
open class RetrievingDataFaliureException(message: String): Excetion(message)  // this exception live in the logic layer
```
the following exceptions inherent form the general exceptions 
```
class WritingToCsvFileFaliureException(): StoringDataFaliureException("fail to write to csv file")
class ReadingFromCsvFileFaliureException(): RetrievingDataFaliureException("fail to read csv file")
class PushingDataToMongoServerFaliureException(): StoringDataFaliureException("fail to push data to mongo server ")
class FetchingDataFromMongoServerFailureException(): RetrievingDataFaliureException("fail to fetch data from mongo server")
```
look and see if other refactors are necessary

### PR DESCRIPTION
**Pull request by ElhamFadel**

### CODE REVIEW

File: src/main/kotlin/logic/exceptions/exceptions.kt
Comment (Al-Qassim) [inline src/main/kotlin/logic/exceptions/exceptions.kt:1]: I think we don't need to name it planeMaterExceptions (the correct spell is planMateExceptions)

just exceptions is enough

**Comment by Al-Qassim** [comment]
did you tested the app and see if it crashes?

**Comment by Al-Qassim** [comment]
when I disconnect the internet and run the app, it crashes

image

**Comment by Al-Qassim** [comment]
the app didn't crash when I 1. run the app, 2. navigate to the project dashboard, 3. disconnected the internet, 4. selected a project

this very good, but I think we need better messages that describe the problem to the user 

image

File: src/main/kotlin/data/dataSources/mongoDBDataSource/DataBaseConnection.kt [hunk 1]
```diff
@@ -13,7 +14,7 @@ object DatabaseConnection {
     private const val LOGS_COLLECTION_NAME = "logs"
     private const val USERS_COLLECTION_NAME = "users"
 
-    private val mongoUri: String = System.getenv("MONGO_URI")
+    private val mongoUri: String = System.getenv("MONGO_URI")?:throw DataConnectionException("MONGO_URI environment variable not set")
```
Comment (Al-Qassim) [inline src/main/kotlin/data/dataSources/mongoDBDataSource/DataBaseConnection.kt]: where will this exception be handled?

right now, if we just run the app with no environment variable set, it will just crash

image

File: src/main/kotlin/data/dataSources/mongoDBDataSource/DataBaseConnection.kt [hunk 2]
```diff
@@ -13,7 +14,7 @@ object DatabaseConnection {
...
 
     private val client = MongoClients.create(mongoUri)
```
Comment (Al-Qassim) [inline src/main/kotlin/data/dataSources/mongoDBDataSource/DataBaseConnection.kt:18]: line 19 will throw an exception if run the app with no internet

File: src/main/kotlin/data/dataSources/mongoDBDataSource/MongoDBLogsDataSource.kt [hunk 3]
```diff
@@ -12,9 +13,18 @@ class MongoDBLogsDataSource(
...
+        return try{
+            collection.find().map { doc ->
+                try {
+                    mongoParser.documentToLogDto(doc)
+                } catch (e: DataAccessException) {
+                    throw DataParsingException("Failed to parse document: ${e.message}")
+                }
+            }.toList()
+        }catch(e: DataAccessException){
+            throw DataConnectionException("Unexpected error while retrieving logs: ${e.message}")
```
Comment (Al-Qassim) [inline src/main/kotlin/data/dataSources/mongoDBDataSource/MongoDBLogsDataSource.kt]: the `DataConnectionException` is inherated from `DataAccessException`

there is no point in this mapping, other than putting the message

just put the message when every you are throwing the exception

File: src/main/kotlin/data/dataSources/mongoDBDataSource/MongoDBUsersDataSource.kt [hunk 4]
```diff
@@ -35,7 +36,7 @@ class MongoDBUsersDataSource(
 
     override fun addMate(userName: String, hashedPassword: String) {
         val existingUser = collection.find(Filters.eq(MongoDBParse.USERNAME_FIELD, userName)).first()
-        if (existingUser != null) throw IllegalStateException("User with username '$userName' already exists")
+        if (existingUser != null) throw DataOperationException("User with username '$userName' already exists")
```
Comment (Al-Qassim) [inline src/main/kotlin/data/dataSources/mongoDBDataSource/MongoDBUsersDataSource.kt]: right now, the logic and the ui layer, don't know anything about the exceptions in the data layer

these exceptions are handled as Unexpected errors

the correct approach is that they must be mapped (catch and throw) in the repo impl to other exceptions that are defined in the logic layer 

try adding the following to the repo 
```
try {
    // add new mate code 
} catch (e: DataOperationException) {
    throw UserNameAlreadyExistException() // this is defined in the logic and is recognized by the ui
}
```

image

File: src/main/kotlin/data/exceptions/DataAccessException.kt [hunk 5]
```diff
@@ -0,0 +1,13 @@
...
+
+open class DataAccessException(message: String) : Exception(message)
+
+class NoLoggedInUserException(message: String = "No logged-in user found in cache") : DataAccessException(message)
+
+class DataRetrievalFailureException(message: String = "Failed to retrieve data") : DataAccessException(message)
+
+class DataConnectionException(message: String = "Failed to connect to data source") : DataAccessException(message)
+
+class DataOperationException(message: String = "Data operation failed") : DataAccessException(message)
```
Comment (Al-Qassim) [inline src/main/kotlin/data/exceptions/DataAccessException.kt]: I don't think that `DataOperationException` is a type of the `DataAccessException`

`Operation ⊈ Access`

but we can considered it as a data reading error

Comment (Al-Qassim) [reply src/main/kotlin/data/exceptions/DataAccessException.kt]: the only place you are using the DataOperationException  is in the add mate function, when the userName is already taken

we already have an exception for this in the logic layer called `UserNameAlreadyExistException` 

and in the public review, bareq said we have a good tree of exceptions in the logic, of course it's not complete, and you could work on improving it

File: src/main/kotlin/data/exceptions/DataAccessException.kt [hunk 6]
```diff
@@ -0,0 +1,23 @@
...
+
+open class CSVDataAccessException(message: String) : DataAccessException(message)
+
+class CSVFileAccessException(message: String = "Failed to open CSV file") : CSVDataAccessException(message)
+
+class CSVReadFailureException(message: String = "Failed to read CSV data") : CSVDataAccessException(message)
+
+class CSVWriteFailureException(message: String = "Failed to write CSV data") : CSVDataAccessException(message)
+
+class CSVParsingException(message: String = "Failed to parse CSV data") : CSVDataAccessException(message)
```
Comment (ZainabAlnajjar) [inline src/main/kotlin/data/exceptions/DataAccessException.kt]: `DataParsingException`  inherits from   `DataAccessException`, while    `CSVParsingException`  inherits from `CSVDataAccessException`
don't you thing this is an odd structure?
first, `CSVDataAccessException` already inherit from `DataAccessException`
 `DataParsingException`  is not a type of  `DataAccessException`, it can be its own exception type
`CSVParsingException` can inherit from `DataParsingException` since they are both parsing data

File: src/main/kotlin/logic/planeMateException/planeMateException.kt
Comment (ZainabAlnajjar) [inline src/main/kotlin/logic/planeMateException/planeMateException.kt:1]: no need for this exception as Alqassim mentioned

File: src/main/kotlin/logic/planeMateException/planeMateException.kt [hunk 7]
```diff
@@ -0,0 +1,3 @@
+package logic.planeMateException
+
+open class PlaneMateException(message: String) : Exception(message)
```
Comment (ZainabAlnajjar) [inline src/main/kotlin/logic/planeMateException/planeMateException.kt]: no need for this exception as Alqassim mentioned, just use the normal Exception

File: src/main/kotlin/data/exceptions/handleException.kt
Comment (Al-Qassim) [inline src/main/kotlin/data/exceptions/handleException.kt:1]: this is a nice idea, but I think this is an over engineering, it's not even clear and hard to read

also, I think you are trying to make the exception handling code reusable, but I think this didn't make the code less, it looks like the code become more, and was just moved from one place to another

simpler approach was good enough

File: src/main/kotlin/data/dataSources/mongoDBDataSource/DataBaseConnection.kt (hunk 2 above)
Comment (ZainabAlnajjar) [reply src/main/kotlin/data/dataSources/mongoDBDataSource/DataBaseConnection.kt:18]: it throws also when there is no MONGO_URI in env variables

Comment (ElhamFadel) [reply src/main/kotlin/data/dataSources/mongoDBDataSource/DataBaseConnection.kt:18]: we can handle this in view

File: src/main/kotlin/logic/planeMateException/planeMateException.kt (hunk 7 above)
Comment (ElhamFadel) [reply src/main/kotlin/logic/planeMateException/planeMateException.kt]: It just like rename for the exception

Comment (ElhamFadel) [reply src/main/kotlin/logic/planeMateException/planeMateException.kt]: but it's okay

File: src/main/kotlin/logic/planeMateException/AuthenticationConstraints.kt [hunk 8]
```diff
@@ -0,0 +1,8 @@
+package logic.planeMateException
+
+object AuthenticationConstraints {
+    const val MIN_USERNAME_LENGTH = 4
+    const val MAX_USERNAME_LENGTH = 12
+    const val MIN_PASSWORD_LENGTH = 6
+    const val MAX_PASSWORD_LENGTH = 12
+}
```
Comment (Al-Qassim) [inline src/main/kotlin/logic/planeMateException/AuthenticationConstraints.kt]: this is the responsibility of the validator to store these values

not here

File: src/main/kotlin/logic/planeMateException/authenticationExceptions.kt [hunk 9]
```diff
@@ -0,0 +1,18 @@
+package logic.planeMateException
+
+open class AuthenticationException(message: String) : PlaneMateException(message)
+
+class InvalidUserNameLengthException : AuthenticationException(
+    "Username should be between ${AuthenticationConstraints.MIN_USERNAME_LENGTH} and ${AuthenticationConstraints.MAX_USERNAME_LENGTH} characters"
+)
```
Comment (Al-Qassim) [inline src/main/kotlin/logic/planeMateException/authenticationExceptions.kt]: this is not a good exception, it should only say `InvalidUserNameException`, the reason or the conditions for why it's invalide should be in the validator (logic layer), the use case will tell the ui why it's invalide and display it to the user

File: src/main/kotlin/logic/planeMateException/authenticationExceptions.kt [hunk 10]
```diff
@@ -0,0 +1,18 @@
...
+
+class InvalidPasswordException : AuthenticationException(
+    "Password should be between ${AuthenticationConstraints.MIN_PASSWORD_LENGTH} and ${AuthenticationConstraints.MAX_PASSWORD_LENGTH} " +
+            "characters and include at least 1 lowercase and 1 uppercase letter"
+)
+
+class UserNameAlreadyExistException : AuthenticationException("A user with this username already exists")
```
Comment (Al-Qassim) [inline src/main/kotlin/logic/planeMateException/authenticationExceptions.kt]: *`UserNameAlreadyTakenException`

File: src/main/kotlin/logic/planeMateException/authenticationExceptions.kt [hunk 11]
```diff
@@ -0,0 +1,18 @@
...
+
+class UnauthorizedAccessException : AuthenticationException("You do not have permission to perform this action!")
+
+class RegistrationFailedException : AuthenticationException("Unable to register user, please try again or contact support.")
```
Comment (Al-Qassim) [inline src/main/kotlin/logic/planeMateException/authenticationExceptions.kt]: the message of the exception should be used for debugging, not to be printed to the user

File: src/main/kotlin/logic/planeMateException/planeMateException.kt (hunk 7 above)
Comment (Al-Qassim) [inline src/main/kotlin/logic/planeMateException/planeMateException.kt]: what's the reason for this?

**Review by Al-Qassim — APPROVED** [review]

**Comment by ZainabAlnajjar** [comment]
in task and taskState datasources use the result to check if the task  or taskState was really updated like what you did in this sample in project datasource:
```
val result = projectsCollection.updateOne(
                Filters.eq(MongoDBParse.ID_FIELD, projectId.toString()),
                Updates.set(MongoDBParse.IS_DELETED_FIELD, true)
            )
            if (result.matchedCount.toInt() == 0) {
                throw ProjectNotFoundException("Project with ID $projectId not found")
            }
```

**Review by ZainabAlnajjar — APPROVED** [review]
